In [2]:
import numpy as np

In [3]:
array_one = np.array([1,2,3,4])


In [4]:
type(array_one)

numpy.ndarray

In [18]:
a = ([1,2,3,4])

In [19]:
type(a)

list

In [12]:
numbers = [9,8,7,6]
array_two = np.array(numbers)
array_two

array([9, 8, 7, 6])

In [13]:
type(array_two)

numpy.ndarray

In [28]:
arrays_zeros = np.zeros((3,4), dtype=np.int16)

In [29]:
print(arrays_zeros)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [22]:
arrays_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [25]:
array_of_ones = np.ones((3,4),dtype=np.int16)
array_of_ones

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)

In [27]:
arrays_empty = np.empty((2,3), dtype=np.int16)
arrays_empty

array([[257, 257, 257],
       [257, 257, 257]], dtype=int16)

In [31]:
array_eye = np.eye(3)
array_eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [34]:
array_of_evens = np.arange(2,10,2)
array_of_evens

array([2, 4, 6, 8])

In [37]:
array_2d = np.array([(2,4,6), (3,5,7)])
array_2d

array([[2, 4, 6],
       [3, 5, 7]])

In [39]:
b=[(2,4,6), (3,5,7)]
type(b)

list

In [44]:
array_2d.shape

(2, 3)

In [45]:
array_nd = np.arange(6).reshape(3,2) 
array_nd

array([[0, 1],
       [2, 3],
       [4, 5]])

In [47]:
array_ones = np.ones_like(array_nd)
array_ones

array([[1, 1],
       [1, 1],
       [1, 1]])

In [54]:
a = np.arange(24).reshape(2,4,3)

In [55]:
print(a)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [56]:
a = np.array([10,10,10])
b = np.array([5,5,5])

In [57]:
a+b


array([15, 15, 15])

In [58]:
a-b

array([5, 5, 5])

In [66]:
a*b

array([50, 50, 50])

In [67]:
A = np.array( [[1,1],[0,1]] )
B = np.array( [[2,0], [3,4]] )

print('A:\n', A)
print('B:\n', B)

A:
 [[1 1]
 [0 1]]
B:
 [[2 0]
 [3 4]]


In [86]:
ho


NameError: name 'ho' is not defined

In [85]:
## hello

In [84]:
## Heading 

In [87]:
%lsmagic

Available line magics:
%alias  %alias_magic  %autoawait  %autocall  %automagic  %autosave  %bookmark  %cd  %clear  %cls  %colors  %conda  %config  %connect_info  %copy  %ddir  %debug  %dhist  %dirs  %doctest_mode  %echo  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %macro  %magic  %matplotlib  %mkdir  %more  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %pip  %popd  %pprint  %precision  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %ren  %rep  %rerun  %reset  %reset_selective  %rmdir  %run  %save  %sc  %set_env  %store  %sx  %system  %tb  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%capture  %%cmd  %%debug  %%file  %%html  %%javascript  %%js  %%latex  %%markdown  %%perl  %%prun  %%pypy  %%python 